export enum MEMBER_ACTION_TYPES {
  GET_INFORMATION_OF_MEMBER_START= "member/GET_INFORMATION_OF_MEMBER_START",
  GET_INFORMATION_OF_MEMBER_SUCCESS = "member/GET_INFORMATION_OF_MEMBER_SUCCESS",
  GET_INFORMATION_OF_MEMBER_FAILED = "member/GET_INFORMATION_OF_MEMBER_FAILED",

  JOIN_LAB_START = "member/JOIN_LAB_START",
  JOIN_LAB_SUCCESS = "member/JOIN_LAB_SUCCESS",
  JOIN_LAB_FAILED = "member/JOIN_LAB_FAILED",

  LEAVE_LAB_START = "member/LEAVE_LAB_START",
  LEAVE_LAB_FAILED = "member/LEAVE_LAB_FAILED",
  LEAVE_LAB_SUCCESS = "member/LEAVE_LAB_SUCCESS",

  GET_RESEARCH_LIST_START = "member/GET_RESEARCH_LIST_START",
  GET_RESEARCH_LIST_FAILED = "member/GET_RESEARCH_LIST_FAILED",
  GET_RESEARCH_LIST_SUCCESS = "member/GET_RESEARCH_LIST_SUCCESS"
};
